54.15 异常
让我们稍微修改一下，我们的moth处理的那个例子(在932页的54.13.4)

清单 54.10: IncorrectMonthException.java
    
    public class IncorrectMonthException extends Exception
    {
    private int index;
    public IncorrectMonthException(int index)
    {
    this.index = index;
    }
    public int getIndex()
    {
    return index;
    }
    }

清单 54.11: Month2.java


    class Month2
    {
    public static String[] months =
    {
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
    };
    public static String get_month (int i) throws ⤦
    Ç IncorrectMonthException
    {
    if (i<0 || i>11)
    throw new IncorrectMonthException(i);
    return months[i];
    };
    public static void main (String[] args)
    {
    try
    {
    System.out.println(get_month(100));
    }
    catch(IncorrectMonthException e)
    {
    System.out.println("incorrect month ⤦
    Ç index: "+ e.getIndex());
    e.printStackTrace();
    }
    };
    }
    

本质上，IncorrectMonthExceptinClass是继承与Exceptiong类，所以，IncorrectMonth构造函数先别调用，Exception类构造届时放入整数值到唯一的IncorrectMonthException类子段。


    public IncorrectMonthException(int);
    flags: ACC_PUBLIC
    Code:
    stack=2, locals=2, args_size=2
    0: aload_0
    1: invokespecial #1 // Method java/⤦
    Ç lang/Exception."<init>":()V
    4: aload_0
    5: iload_1
    6: putfield #2 // Field index:I
    9: return

getIndex()是一个存储器(引用IncorrectMothnException被传到了LVA的槽0(this),用aload_0取得它， getfield,加载整数值，从对象ireturn返回。

    public int getIndex();
    flags: ACC_PUBLIC
    Code:
    stack=1, locals=1, args_size=1
    0: aload_0
    1: getfield #2 // Field index:I
    4: ireturn

现在我们看看month.class的get_month方法。

清单 54.12: Month2.class
    
    public static java.lang.String get_month(int) throws ⤦
    Ç IncorrectMonthException;
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
    stack=3, locals=1, args_size=1
    0: iload_0
    1: iflt 10
    4: iload_0
    5: bipush 11
    7: if_icmple 19
    10: new #2 // class ⤦
    Ç IncorrectMonthException
    13: dup
    14: iload_0
    15: invokespecial #3 // Method ⤦
    Ç IncorrectMonthException."<init>":(I)V
    18: athrow
    19: getstatic #4 // Field months:[⤦
    Ç Ljava/lang/String;
    22: iload_0
    23: aaload
    24: areturn

949

iflt 在行偏移1 ，如果小于

在无效下标的情况，一个新对应被用新的指令创建的，在行偏移10行，对象类型是被传递的指令操作数。（这个IncorrectMonthException）
它的构造被调用，整数下表被传递到栈顶（栈顶偏移15）
在时间控制流开始的的18行偏移，对象易经准备被构造了，现在Athrow指令取得新构造函数的引用，并且给JVM信号去发现合适的异常句柄。
Athrow指令在这个不返回到控制流，所以在19行偏移，另外的一个基本模块，无异常无关，我们从7行偏移得知。
句柄怎么工作？ main()在inmonth2.class

清单 54.13: Month2.class

    public static void main(java.lang.String[]);
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
    stack=3, locals=2, args_size=1
    0: getstatic #5 // Field java/⤦
    Ç lang/System.out:Ljava/io/PrintStream;
    3: bipush 100
    5: invokestatic #6 // Method ⤦
    Ç get_month:(I)Ljava/lang/String;
    8: invokevirtual #7 // Method java/io⤦
    Ç /PrintStream.println:(Ljava/lang/String;)V
    11: goto 47
    14: astore_1
    15: getstatic #5 // Field java/⤦
    Ç lang/System.out:Ljava/io/PrintStream;
    18: new #8 // class java/⤦
    Ç lang/StringBuilder
    21: dup
    22: invokespecial #9 // Method java/⤦
    Ç lang/StringBuilder."<init>":()V
    25: ldc #10 // String ⤦
    Ç incorrect month index:
    27: invokevirtual #11 // Method java/⤦
    Ç lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/⤦
    Ç StringBuilder;
    30: aload_1
    31: invokevirtual #12 // Method ⤦
    Ç IncorrectMonthException.getIndex:()I
    34: invokevirtual #13 // Method java/⤦
    Ç lang/StringBuilder.append:(I)Ljava/lang/StringBuilder;
    37: invokevirtual #14 // Method java/⤦
    Ç lang/StringBuilder.toString:()Ljava/lang/String;
    40: invokevirtual #7 // Method java/io⤦
    Ç /PrintStream.println:(Ljava/lang/String;)V
    43: aload_1
    44: invokevirtual #15 // Method ⤦
    Ç IncorrectMonthException.printStackTrace:()V
    47: return
    Exception table:
    from to target type
    0 11 14 Class IncorrectMonthException



950
这是一个异常表，在行偏移0-11（包括）行，一个IncorrectinMonthException异常可能发生，如果发生，控制流传递到314行，确实
main程序在11行偏移结束，在14行捕获开始，它在这个可能的在这个无条件的区域跳转。但是JVM会传递并执行这个异常。
第一个astore_1(在行偏移14)取得，到来异常的异常对象的引用，存储在LVA的槽参数1之后。getIndex()方法（这个异常对象）
会在31行偏移调用。引用当前异常对象，被传递前（30行偏移）所有字符串处理代码的代码复位，是字符串的处理代码。
？？？？？？

转换字符串用tostirng()方法，文本字符串（就像叫我们之前考虑的）println（）和printStackTrace(1)被调用，PrintStackTrace(1)调用
结束之后，异常被捕获，我们处理正常的函数，在47行偏移，结束main（）函数return ,但是没有其他任何的代码执行，如果没有
发生异常。


这是一个例子。IDA如果显示IDA，异常的范围，

清单54.14 我从我的计算机中发现了 random.class 文件

    
    .catch java/io/FileNotFoundException from met001_335 to ⤦
    Ç met001_360\
    using met001_360
    .catch java/io/FileNotFoundException from met001_185 to ⤦
    Ç met001_214\
    using met001_214
    .catch java/io/FileNotFoundException from met001_181 to ⤦
    Ç met001_192\
    using met001_195
    951
    CHAPTER 54. JAVA 54.16. CLASSES
    .catch java/io/FileNotFoundException from met001_155 to ⤦
    Ç met001_176\
    using met001_176
    .catch java/io/FileNotFoundException from met001_83 to ⤦
    Ç met001_129 using \
    met001_129
    .catch java/io/FileNotFoundException from met001_42 to ⤦
    Ç met001_66 using \
    met001_69
    .catch java/io/FileNotFoundException from met001_begin to ⤦
    Ç met001_37\
    using met001_37





